### PR TITLE
SISRP-8175 Design and implement a simple web server for the QA automation framework

### PR DESCRIPTION
**Pull request by mDibyo**
https://jira.berkeley.edu/browse/SISRP-8175

### CODE REVIEW

**Comment by mDibyo** [comment]
Ready to review.

**Comment by christianvuerings** [comment]
@mDibyo lgtm
@ctweney - could you also have a look?

**Comment by ctweney** [comment]
I think I am missing the context here, and the requirements that drive the need for this HTTP server. I have a lot of questions: 

Why is it desirable to expose test-running features over HTTP? 

How will users be authenticated? 

Can any IP address hit the server? 

Can a flood of GET requests cause multiple test executions? 

If so, will those cause load problems for the BCS or CalCentral servers? 

What data is exposed over HTTP in the test reports? 

Where will the server process be hosted? 

Couldn't all of this be done more securely and simply from the command line with "bundle exec cucumber"?

**Comment by mDibyo** [comment]
@ctweney I will answer your questions inline. I am sorry for not documenting this server more rigorously. Can I copy over this response into the ticket as documentation?

**First some background**:
One of the goals of this QA Test Automation framework set by George, has been to make it simple to use both by technical and non-technical users. This has informed many of the design decisions on the framework. For instance, the decision to use the Cucumber test framework.
Besides that decision, I have tried to design the framework in such a way that users never have to go to the command line. They can add Cucumber feature files to a shared GDrive folder. They can run tests (or a subset of them), and see the results through an online interface.

This is the reasoning behind the addition of an HTTP server to the framework. People should be able to request tests by going to a specific link. The answers to some of your questions are implemented in PR #4 (SISRP-8826 https://jira.berkeley.edu/browse/SISRP-8826).

**Now for your questions**:
Why is it desirable to expose test-running features over HTTP?
_The last paragraph above._

How will users be authenticated?
_The test service will be placed behind CalNet Authentication Service, and on HTTPS._

Can any IP address hit the server?
_No. The framework will be running inside a VM on an internal server. Only people on the UC Berkeley network can hit the server._

Can a flood of GET requests cause multiple test executions?
_They can currently. We can rate limit number of requests per user if that turns out to be a problem._

If so, will those cause load problems for the BCS or CalCentral servers?
_In [SISRP-8826](https://github.com/ucberkeley/sis-qa-test-auto/pull/4), I have fleshed out the execution into a ProcessPoolExecutor. With this new system, the maximum number of concurrent test executions will be equal to the number of cores on the host machine.  (the Pool maintains a queue of pending tests. ) We can reduce this number to reduce load. To increase it, we would have to essentially get a machine with more cores (or work with multiple machines)._

What data is exposed over HTTP in the test reports?
_Full Cucumber test reports will be exposed, so Cucumber test steps and whether they succeeded, but no credentials. We will anyway shift to HTTPS._

Where will the server process be hosted?
_The server process will be run from inside the Docker container for the framework._

Couldn't all of this be done more securely and simply from the command line with "bundle exec cucumber"?
_Yes. But we are also trying to cater to non-technical users._

**Comment by mDibyo** [comment]
I would like to add that the changes made in this PR can be summed in the description for one of the commits: https://github.com/mDibyo/sis-qa-test-auto/commit/37d3bcbbb4223ab1401d4b60245fd13ec7e47386

**Comment by ctweney** [comment]
Thanks for the explanations! This is really great work. Looks good to me -- just make sure CAS authentication is required for access before exposing this on a shared VM.

**Pull request merged**
